--STORED PROCEDURES
--BOOK ISSUE INSERT STATEMENT
INSERT 
INTO 
LMS_BOOK_ISSUE
(MEMBER_ID,BOOK_ID,DATE_ISSUE,DATE_RETURN)
VALUES
(100001,1001,'2013-01-1',NULL),
--(100001,1001,'2013-01-1','2013-01-10'),
(100002,1002,'2013-02-10','2013-03-13'),
(100005,1003,'2013-03-06','2013-05-15'),
(100007,1004,'2013-03-12','2013-04-15'),
(100009,1004,'2013-12-12',NULL)

SELECT * FROM LMS_BOOK_ISSUE

--HOW TO CHANGE THE BOOK STATUS

--BOOK RETURN UPDATE STATEMENT
UPDATE LMS_BOOK_ISSUE
SET
DATE_RETURN='2013-04-5'
WHERE MEMBER_ID='100001' AND BOOK_ID='1001'


--ADDING NEW TYPE OF BOOK
INSERT 
INTO 
LMS_BOOK_DETAILS
(BOOK_CODE,BOOK_TITLE,AUTHOR,CATEGORY,PUBLICATIONS,BOOK_EDITION,PRICE)
VALUES 
('JAV001','Java The Complete Reference','Herbert Schildt','JAVA','McGraw hill',8,421)


--ADDING NEW COPIES IN ALL_BOOKS TABLE
INSERT
INTO
LMS_ALL_BOOKS
(BOOK_CODE,BOOK_AVAILABILITY,SUPPLIER_ID)
VALUES
('JAV001','Y',101)





--sdsCurrentBooks data source Query
SELECT  LMS_BOOK_ISSUE.BOOK_ID as 'Book ID', 
LMS_BOOK_DETAILS.BOOK_TITLE as 'Title', 
LMS_BOOK_ISSUE.DATE_ISSUE as 'Issue Date', 
LMS_BOOK_ISSUE.DATE_DUE as 'Due Date', 
LMS_BOOK_ISSUE.DAYS_DELAYED as 'Days Delayed', 
LMS_BOOK_ISSUE.FINE_AMOUNT as 'Fine Amount' 
FROM LMS_BOOK_ISSUE 
INNER JOIN LMS_MEMBER_DETAILS ON LMS_MEMBER_DETAILS.MEMBER_ID=LMS_BOOK_ISSUE.MEMBER_ID
INNER JOIN LMS_ALL_BOOKS ON LMS_ALL_BOOKS.BOOK_ID = LMS_BOOK_ISSUE.BOOK_ID 
INNER JOIN LMS_BOOK_DETAILS ON LMS_BOOK_DETAILS.BOOK_CODE = LMS_ALL_BOOKS.BOOK_CODE
WHERE LMS_MEMBER_DETAILS.MEMBER_ID=100001 AND LMS_BOOK_ISSUE.DATE_RETURN IS NULL

--sdsMemberDetails Query
SELECT 
MEMBER_ID as 'Member ID', 
MEMBER_NAME as 'Name', 
PHONE_NUMBER as 'Phone Number', 
MEMBER_EMAIL as 'Email', 
SECURITY_QUESTION as 'Security Question', 
ANSWER as 'Answer', 
ID_PROOF_TYPE as 'ID Proof', 
ID_PROOF_NUMBER as 'ID Proof Number', 
DATE_REGISTER as 'Register Date'
FROM LMS_MEMBER_DETAILS
WHERE LMS_MEMBER_DETAILS.MEMBER_ID=100001