

--TRIGGER FOR BOOK ISSUE INSERT
CREATE TRIGGER Toogle_Book_Availability_On_Book_Issue_Insert ON LMS_BOOK_ISSUE 
for INSERT
AS
UPDATE LMS_ALL_BOOKS
SET LMS_ALL_BOOKS.BOOK_AVAILABILITY='N'
WHERE 
LMS_ALL_BOOKS.BOOK_ID=(SELECT BOOK_ID FROM inserted)



--TRIGGER FOR BOOK RETURN UPDATE
CREATE TRIGGER Toogle_Book_Availability_On_Book_Issue_Update ON LMS_BOOK_ISSUE
FOR	UPDATE
AS
UPDATE LMS_ALL_BOOKS
SET LMS_ALL_BOOKS.BOOK_AVAILABILITY='Y'
WHERE
LMS_ALL_BOOKS.BOOK_ID=(SELECT BOOK_ID FROM inserted)


DROP TRIGGER Toogle_Book_Availability_On_Book_Issue_Insert
DROP TRIGGER Toogle_Book_Availability_On_Book_Issue_Update